[tool.poetry]
name = "tipo-avito"
version = "0.1.0"
description = ""
authors = ["Igotres <irapb@inbox.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.1"
pillow = "^10.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
